import { Inter as FontSans } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { Metadata } from 'next';
import { Toaster } from '@/components/ui/sonner';
import NextAuthProvider from '@/providers/authProvider';

const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={cn('h-screen bg-background font-sans antialiased', fontSans.variable)}>
				<NextAuthProvider>
					{children}
					<Toaster />
				</NextAuthProvider>
			</body>
		</html>
	);
}
